"""
===============================================================================
STEP 13 — COMPARATIVE STRUCTURAL ANALYSIS
           OF ALL 9 PRIORITIZED PNPLA3 VARIANTS
===============================================================================

Project:
    MASLD–PNPLA3 Variant Analysis

Purpose:
    Comparative structural analysis of the nine variants selected in Step 9F.

IMPORTANT:
    - Step 9F is the authoritative candidate dataset.
    - Protein_Position is the authoritative residue-position field.
    - The validated Step 10 WT PNPLA3 structure is used as the common reference.
    - Every mutant is generated by TRUE PyMOL side-chain mutagenesis.
    - No residue-name-only substitution is performed.
    - No energy minimization or molecular dynamics is performed in Step 13.
    - Structural-impact scores generated here are comparative analysis metrics,
      NOT pathogenicity probabilities.

PyMOL:
    This script is intended to be executed with:

    %USERPROFILE%\miniconda3\envs\pymol\python.exe

===============================================================================
"""

from pathlib import Path
import sys
import os
import re
import json
import shutil
import subprocess
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")


# =============================================================================
# CONFIGURATION
# =============================================================================

PROJECT_NAME = "MASLD_PNPLA3"

STEP9F_FILENAME = (
    "pnpla3_step9f_final_candidate_selection_FINAL.csv"
)

EXPECTED_VARIANTS = 82
EXPECTED_STRUCTURAL_CANDIDATES = 9

EXPECTED_UNIPROT = "Q9NST1"

WT_PDB_FILENAME = "PNPLA3_WT.pdb"

STEP10_PLDDT_FILENAME = "Table_S10_10_local_pLDDT.csv"

LOCAL_RMSD_WINDOW = 10

CONTACT_DISTANCE = 4.5

POLAR_CONTACT_DISTANCE = 3.5

LOCAL_ENVIRONMENT_DISTANCE = 5.0

CATALYTIC_CONTEXT_CUTOFF = 10.0


# =============================================================================
# PATHS
# =============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent

PROJECT_ROOT = SCRIPT_DIR.parent

STEP10_DIR = (
    PROJECT_ROOT
    / "RESULTS"
    / "STEP10_STRUCTURAL_ANALYSIS"
)

STEP13_DIR = (
    PROJECT_ROOT
    / "RESULTS"
    / "STEP13_COMPARATIVE_STRUCTURAL_ANALYSIS"
)

STEP10_STRUCTURE_DIR = (
    STEP10_DIR
    / "structures"
)

STEP10_WT_DIR = (
    STEP10_STRUCTURE_DIR
    / "WT"
)

STEP10_TABLE_DIR = (
    STEP10_DIR
    / "tables"
)

STEP13_STRUCTURE_DIR = (
    STEP13_DIR
    / "structures"
)

STEP13_WT_DIR = (
    STEP13_STRUCTURE_DIR
    / "WT_REFERENCE"
)

STEP13_MUTANT_DIR = (
    STEP13_STRUCTURE_DIR
    / "MUTANTS"
)

TABLE_DIR = (
    STEP13_DIR
    / "tables"
)

FIGURE_DIR = (
    STEP13_DIR
    / "figures"
)

QC_DIR = (
    STEP13_DIR
    / "QC"
)

LOG_DIR = (
    STEP13_DIR
    / "logs"
)

TEMP_DIR = (
    STEP13_DIR
    / "temporary"
)


for directory in [
    STEP13_DIR,
    STEP13_STRUCTURE_DIR,
    STEP13_WT_DIR,
    STEP13_MUTANT_DIR,
    TABLE_DIR,
    FIGURE_DIR,
    QC_DIR,
    LOG_DIR,
    TEMP_DIR,
]:
    directory.mkdir(
        parents=True,
        exist_ok=True
    )


LOG_FILE = (
    LOG_DIR
    / "Step13_execution.log"
)


# =============================================================================
# LOGGING
# =============================================================================

def log(message=""):

    print(message)

    with open(
        LOG_FILE,
        "a",
        encoding="utf-8"
    ) as handle:

        handle.write(
            str(message)
            + "\n"
        )


def section(title):

    log("")
    log("=" * 78)
    log(title)
    log("=" * 78)


def subsection(title):

    log("")
    log("-" * 78)
    log(title)
    log("-" * 78)


def status(label, passed, details=None):

    text = (
        f"{label:<58} "
        f"{'PASS' if passed else 'FAIL'}"
    )

    if details is not None:
        text += f" — {details}"

    log(text)


# =============================================================================
# JSON SAFE
# =============================================================================

def json_safe(value):

    if isinstance(value, np.generic):
        return value.item()

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, dict):

        return {
            str(key): json_safe(val)
            for key, val in value.items()
        }

    if isinstance(value, list):

        return [
            json_safe(item)
            for item in value
        ]

    if isinstance(value, tuple):

        return [
            json_safe(item)
            for item in value
        ]

    return value


def write_json(path, data):

    with open(
        path,
        "w",
        encoding="utf-8"
    ) as handle:

        json.dump(
            json_safe(data),
            handle,
            indent=4
        )


# =============================================================================
# BIOPYTHON
# =============================================================================

try:

    from Bio.PDB import (
        PDBParser,
        Superimposer,
    )

    from Bio.PDB.Polypeptide import is_aa

    from Bio.SeqUtils import seq1

except ImportError as exc:

    log(
        "ERROR: Biopython is required."
    )

    log(str(exc))

    sys.exit(1)


# =============================================================================
# MATPLOTLIB
# =============================================================================

try:

    import matplotlib

    matplotlib.use("Agg")

    import matplotlib.pyplot as plt

except ImportError as exc:

    log(
        "ERROR: matplotlib is required."
    )

    log(str(exc))

    sys.exit(1)


# =============================================================================
# PYMOL
# =============================================================================

try:

    import pymol

    pymol.finish_launching(
        [
            "pymol",
            "-cq"
        ]
    )

    from pymol import cmd

except Exception as exc:

    log(
        "ERROR: PyMOL Python API could not be initialized."
    )

    log(str(exc))

    log("")
    log(
        "Run this script with:"
    )
    log(
        r'%USERPROFILE%\miniconda3\envs\pymol\python.exe '
        r'"SCRIPTS\13_comparative_structural_analysis_all9.py"'
    )

    sys.exit(1)


# =============================================================================
# AMINO ACID TABLES
# =============================================================================

AA3_TO_AA1 = {

    "ALA": "A",
    "ARG": "R",
    "ASN": "N",
    "ASP": "D",
    "CYS": "C",
    "GLN": "Q",
    "GLU": "E",
    "GLY": "G",
    "HIS": "H",
    "ILE": "I",
    "LEU": "L",
    "LYS": "K",
    "MET": "M",
    "PHE": "F",
    "PRO": "P",
    "SER": "S",
    "THR": "T",
    "TRP": "W",
    "TYR": "Y",
    "VAL": "V",
}


AA1_TO_AA3 = {
    value: key
    for key, value in AA3_TO_AA1.items()
}


AA1_TO_NAME = {

    "A": "Alanine",
    "R": "Arginine",
    "N": "Asparagine",
    "D": "Aspartate",
    "C": "Cysteine",
    "Q": "Glutamine",
    "E": "Glutamate",
    "G": "Glycine",
    "H": "Histidine",
    "I": "Isoleucine",
    "L": "Leucine",
    "K": "Lysine",
    "M": "Methionine",
    "F": "Phenylalanine",
    "P": "Proline",
    "S": "Serine",
    "T": "Threonine",
    "W": "Tryptophan",
    "Y": "Tyrosine",
    "V": "Valine",
}


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def safe_seq1(resname):

    resname = str(
        resname
    ).upper().strip()

    if resname in AA3_TO_AA1:
        return AA3_TO_AA1[resname]

    try:

        return seq1(
            resname
        )

    except Exception:

        return "X"


def residue_number(residue):

    return int(
        residue.id[1]
    )


def get_structure_residue(chain, position):

    for residue in chain:

        try:

            number = residue_number(
                residue
            )

        except Exception:

            continue

        if number == position:

            return residue

    return None


def get_protein_residues(chain):

    return [
        residue
        for residue in chain
        if is_aa(
            residue,
            standard=False
        )
    ]


def get_chain(structure, preferred_chain="A"):

    model = next(
        structure.get_models()
    )

    if preferred_chain in model.child_dict:

        return model[
            preferred_chain
        ]

    chains = list(
        model.get_chains()
    )

    if not chains:

        return None

    return chains[0]


def load_structure(path, structure_id):

    parser = PDBParser(
        QUIET=True
    )

    return parser.get_structure(
        structure_id,
        str(path)
    )


def minimum_heavy_atom_distance(
    residue_a,
    residue_b
):

    atoms_a = [
        atom
        for atom in residue_a
        if str(atom.element).upper() != "H"
    ]

    atoms_b = [
        atom
        for atom in residue_b
        if str(atom.element).upper() != "H"
    ]

    if not atoms_a or not atoms_b:

        return np.nan

    minimum = np.inf

    for atom_a in atoms_a:

        for atom_b in atoms_b:

            distance = np.linalg.norm(
                atom_a.coord
                - atom_b.coord
            )

            if distance < minimum:

                minimum = distance

    return float(minimum)


def get_residue_plddt(residue):

    values = []

    for atom in residue:

        try:

            value = float(
                atom.bfactor
            )

            if value >= 0:

                values.append(
                    value
                )

        except Exception:

            continue

    if not values:

        return np.nan

    return float(
        np.mean(values)
    )


def get_mean_plddt(chain):

    values = []

    for residue in get_protein_residues(
        chain
    ):

        value = get_residue_plddt(
            residue
        )

        if not np.isnan(value):

            values.append(
                value
            )

    if not values:

        return np.nan

    return float(
        np.mean(values)
    )


def get_ca_atoms_by_position(
    chain
):

    output = {}

    for residue in get_protein_residues(
        chain
    ):

        position = residue_number(
            residue
        )

        if "CA" in residue:

            output[position] = residue[
                "CA"
            ]

    return output


def get_backbone_atoms_by_key(
    chain
):

    output = {}

    for residue in get_protein_residues(
        chain
    ):

        position = residue_number(
            residue
        )

        for atom_name in [
            "N",
            "CA",
            "C",
        ]:

            if atom_name in residue:

                output[
                    (
                        position,
                        atom_name
                    )
                ] = residue[
                    atom_name
                ]

    return output


def calculate_rmsd(
    fixed_atoms,
    moving_atoms
):

    if len(fixed_atoms) != len(
        moving_atoms
    ):

        return np.nan

    if len(fixed_atoms) < 1:

        return np.nan

    superimposer = Superimposer()

    superimposer.set_atoms(
        fixed_atoms,
        moving_atoms
    )

    return float(
        superimposer.rms
    )


def parse_catalytic_position(
    value
):

    if pd.isna(value):

        return np.nan

    text = str(
        value
    )

    matches = re.findall(
        r"\b([0-9]{1,4})\b",
        text
    )

    if not matches:

        return np.nan

    return int(
        matches[0]
    )


def normalize_bool(value):

    text = str(
        value
    ).strip().upper()

    return text in [
        "YES",
        "TRUE",
        "1",
        "Y",
    ]


def physicochemical_impact(
    wt,
    mut
):

    if wt == mut:

        return 0

    groups = {

        "hydrophobic": set(
            "AVILMFW"
        ),

        "polar": set(
            "STNQYC"
        ),

        "positive": set(
            "KRH"
        ),

        "negative": set(
            "DE"
        ),

        "special": set(
            "GP"
        ),
    }

    wt_groups = {
        name
        for name, residues in groups.items()
        if wt in residues
    }

    mut_groups = {
        name
        for name, residues in groups.items()
        if mut in residues
    }

    if (
        wt in "DE"
        and mut in "AVILMFW"
    ):

        return 5

    if (
        wt in "KRH"
        and mut in "AVILMFW"
    ):

        return 5

    if (
        wt in "AVILMFW"
        and mut in "DEKRH"
    ):

        return 5

    if wt_groups != mut_groups:

        return 3

    return 1


def candidate_polar_contacts(
    chain,
    target_position,
    cutoff=POLAR_CONTACT_DISTANCE
):

    polar_elements = {
        "N",
        "O",
        "S",
    }

    target = get_structure_residue(
        chain,
        target_position
    )

    records = []

    if target is None:

        return records

    target_atoms = [
        atom
        for atom in target
        if str(atom.element).upper()
        in polar_elements
    ]

    for residue in get_protein_residues(
        chain
    ):

        position = residue_number(
            residue
        )

        if position == target_position:

            continue

        partner_atoms = [
            atom
            for atom in residue
            if str(atom.element).upper()
            in polar_elements
        ]

        for atom_a in target_atoms:

            for atom_b in partner_atoms:

                distance = np.linalg.norm(
                    atom_a.coord
                    - atom_b.coord
                )

                if distance <= cutoff:

                    records.append(
                        {
                            "Target_Position":
                                target_position,

                            "Target_Atom":
                                atom_a.name.strip(),

                            "Partner_Position":
                                position,

                            "Partner_Residue":
                                residue.resname,

                            "Partner_AA":
                                safe_seq1(
                                    residue.resname
                                ),

                            "Partner_Atom":
                                atom_b.name.strip(),

                            "Distance_A":
                                float(distance),
                        }
                    )

    records.sort(
        key=lambda item:
        item["Distance_A"]
    )

    return records


def build_contact_map(
    chain,
    target_position,
    cutoff=CONTACT_DISTANCE
):

    target = get_structure_residue(
        chain,
        target_position
    )

    records = []

    if target is None:

        return records

    for residue in get_protein_residues(
        chain
    ):

        position = residue_number(
            residue
        )

        if position == target_position:

            continue

        distance = minimum_heavy_atom_distance(
            target,
            residue
        )

        if np.isnan(distance):

            continue

        if distance <= cutoff:

            records.append(
                {
                    "Residue_Position":
                        position,

                    "Residue_Name":
                        residue.resname,

                    "Residue_AA":
                        safe_seq1(
                            residue.resname
                        ),

                    "Minimum_Heavy_Atom_Distance_A":
                        distance,
                }
            )

    records.sort(
        key=lambda item:
        item[
            "Minimum_Heavy_Atom_Distance_A"
        ]
    )

    return records


def build_local_environment(
    chain,
    target_position,
    radius=LOCAL_ENVIRONMENT_DISTANCE
):

    target = get_structure_residue(
        chain,
        target_position
    )

    records = []

    if target is None:

        return records

    for residue in get_protein_residues(
        chain
    ):

        position = residue_number(
            residue
        )

        if position == target_position:

            continue

        distance = minimum_heavy_atom_distance(
            target,
            residue
        )

        if np.isnan(distance):

            continue

        if distance <= radius:

            records.append(
                {
                    "Residue_Position":
                        position,

                    "Residue_Name":
                        residue.resname,

                    "Residue_AA":
                        safe_seq1(
                            residue.resname
                        ),

                    "Minimum_Heavy_Atom_Distance_A":
                        float(distance),
                }
            )

    records.sort(
        key=lambda item:
        item[
            "Minimum_Heavy_Atom_Distance_A"
        ]
    )

    return records


def build_local_ca_rmsd_profile(
    wt_chain,
    mutant_chain,
    target_position,
    window=LOCAL_RMSD_WINDOW
):

    records = []

    wt_ca = get_ca_atoms_by_position(
        wt_chain
    )

    mut_ca = get_ca_atoms_by_position(
        mutant_chain
    )

    common_positions = sorted(
        set(wt_ca)
        &
        set(mut_ca)
    )

    local_positions = [
        position
        for position in common_positions
        if abs(
            position - target_position
        ) <= window
    ]

    if len(local_positions) < 3:

        return records

    fixed_atoms = [
        wt_ca[position]
        for position in local_positions
    ]

    moving_atoms = [
        mut_ca[position]
        for position in local_positions
    ]

    local_rmsd = calculate_rmsd(
        fixed_atoms,
        moving_atoms
    )

    for position in local_positions:

        records.append(
            {
                "Target_Position":
                    target_position,

                "Residue_Position":
                    position,

                "Relative_Position":
                    position - target_position,

                "Local_Window":
                    f"+/-{window}",

                "Local_CA_RMSD_A":
                    local_rmsd,
            }
        )

    return records


def generate_mutant_with_pymol(
    wt_pdb,
    mutant_pdb,
    position,
    mutant_three,
    mutant_one,
    chain_id="A"
):

    if mutant_pdb.exists():

        mutant_pdb.unlink()

    object_name = (
        "PNPLA3_WT_MUTATION"
    )

    target_selection = (
        "target_residue"
    )

    try:

        cmd.reinitialize()

        cmd.load(
            str(wt_pdb),
            object_name
        )

        # -------------------------------------------------------------
        # Validate WT residue before mutation
        # -------------------------------------------------------------

        cmd.select(
            target_selection,
            (
                f"{object_name} and "
                f"chain {chain_id} and "
                f"resi {position}"
            )
        )

        selection_count = cmd.count_atoms(
            target_selection
        )

        if selection_count <= 0:

            raise RuntimeError(
                "Target residue selection returned "
                "zero atoms."
            )

        # -------------------------------------------------------------
        # IMPORTANT:
        # This is the exact working PyMOL 3.1.0 sequence used in
        # Step 10.
        # -------------------------------------------------------------

        cmd.wizard(
            "mutagenesis"
        )

        wiz = cmd.get_wizard()

        if wiz is None:

            raise RuntimeError(
                "PyMOL mutagenesis wizard could not "
                "be initialized."
            )

        wiz.set_mode(
            mutant_three
        )

        wiz.do_select(
            target_selection
        )

        try:

            cmd.refresh_wizard()

        except Exception:

            pass

        # Apply selected rotamer.
        wiz.apply()

        # Exit wizard.
        cmd.set_wizard()

        # -------------------------------------------------------------
        # Save actual remodeled structure
        # -------------------------------------------------------------

        cmd.save(
            str(mutant_pdb),
            object_name
        )

        cmd.delete(
            "all"
        )

    except Exception as exc:

        try:

            cmd.set_wizard()

        except Exception:

            pass

        try:

            cmd.delete(
                "all"
            )

        except Exception:

            pass

        raise RuntimeError(
            f"PyMOL mutagenesis failed for "
            f"position {position} -> {mutant_three}: "
            f"{exc}"
        )


def validate_mutant_structure(
    mutant_pdb,
    position,
    expected_one,
    expected_three
):

    structure = load_structure(
        mutant_pdb,
        "MUTANT"
    )

    chain = get_chain(
        structure,
        "A"
    )

    if chain is None:

        return {
            "passed": False,
            "reason":
                "No chain found",
        }

    residue = get_structure_residue(
        chain,
        position
    )

    if residue is None:

        return {
            "passed": False,
            "reason":
                "Target residue not found",
        }

    observed_one = safe_seq1(
        residue.resname
    )

    atom_names = {
        atom.name.strip()
        for atom in residue
    }

    expected_sidechain_atoms = {

        "A": {"CB"},
        "R": {"CB", "CG", "CD", "NE"},
        "N": {"CB", "CG"},
        "D": {"CB", "CG", "OD1", "OD2"},
        "C": {"CB", "SG"},
        "Q": {"CB", "CG", "CD"},
        "E": {"CB", "CG", "CD"},
        "G": set(),
        "H": {"CB", "CG", "ND1", "CD2"},
        "I": {"CB", "CG1", "CG2", "CD1"},
        "L": {"CB", "CG", "CD1", "CD2"},
        "K": {"CB", "CG", "CD", "CE"},
        "M": {"CB", "CG", "SD", "CE"},
        "F": {"CB", "CG", "CD1", "CD2"},
        "P": {"CB", "CG", "CD"},
        "S": {"CB", "OG"},
        "T": {"CB", "OG1", "CG2"},
        "W": {"CB", "CG", "CD1", "CD2"},
        "Y": {"CB", "CG", "CD1", "CD2", "OH"},
        "V": {"CB", "CG1", "CG2"},
    }

    expected_atoms = expected_sidechain_atoms.get(
        expected_one,
        set()
    )

    sidechain_atoms_present = (
        expected_atoms.issubset(
            atom_names
        )
    )

    return {

        "passed":
            (
                observed_one == expected_one
                and sidechain_atoms_present
            ),

        "reason":
            "Validated",

        "observed_one":
            observed_one,

        "observed_three":
            residue.resname,

        "expected_one":
            expected_one,

        "expected_three":
            expected_three,

        "sidechain_atoms_present":
            sidechain_atoms_present,

        "atom_names":
            sorted(atom_names),
    }


def calculate_structural_comparison(
    wt_structure,
    mutant_structure,
    chain_id
):

    wt_chain = get_chain(
        wt_structure,
        chain_id
    )

    mutant_chain = get_chain(
        mutant_structure,
        chain_id
    )

    if wt_chain is None:

        raise RuntimeError(
            "WT chain not found."
        )

    if mutant_chain is None:

        raise RuntimeError(
            "Mutant chain not found."
        )

    wt_ca = get_ca_atoms_by_position(
        wt_chain
    )

    mutant_ca = get_ca_atoms_by_position(
        mutant_chain
    )

    common_ca_positions = sorted(
        set(wt_ca)
        &
        set(mutant_ca)
    )

    fixed_ca = [
        wt_ca[position]
        for position in common_ca_positions
    ]

    moving_ca = [
        mutant_ca[position]
        for position in common_ca_positions
    ]

    global_ca_rmsd = calculate_rmsd(
        fixed_ca,
        moving_ca
    )

    wt_backbone = get_backbone_atoms_by_key(
        wt_chain
    )

    mutant_backbone = get_backbone_atoms_by_key(
        mutant_chain
    )

    common_backbone_keys = sorted(
        set(wt_backbone)
        &
        set(mutant_backbone)
    )

    fixed_backbone = [
        wt_backbone[key]
        for key in common_backbone_keys
    ]

    moving_backbone = [
        mutant_backbone[key]
        for key in common_backbone_keys
    ]

    global_backbone_rmsd = calculate_rmsd(
        fixed_backbone,
        moving_backbone
    )

    return {
        "global_ca_rmsd":
            global_ca_rmsd,

        "global_backbone_rmsd":
            global_backbone_rmsd,

        "common_ca_residues":
            len(common_ca_positions),

        "common_backbone_atoms":
            len(common_backbone_keys),
    }


def calculate_local_rmsd(
    wt_chain,
    mutant_chain,
    target_position,
    window=LOCAL_RMSD_WINDOW
):

    wt_ca = get_ca_atoms_by_position(
        wt_chain
    )

    mutant_ca = get_ca_atoms_by_position(
        mutant_chain
    )

    positions = sorted(
        set(wt_ca)
        &
        set(mutant_ca)
    )

    local_positions = [
        position
        for position in positions
        if abs(
            position - target_position
        ) <= window
    ]

    fixed = [
        wt_ca[position]
        for position in local_positions
    ]

    moving = [
        mutant_ca[position]
        for position in local_positions
    ]

    if len(fixed) < 3:

        return np.nan

    return calculate_rmsd(
        fixed,
        moving
    )


def contact_comparison(
    wt_chain,
    mutant_chain,
    target_position
):

    wt_contacts = build_contact_map(
        wt_chain,
        target_position
    )

    mutant_contacts = build_contact_map(
        mutant_chain,
        target_position
    )

    wt_dict = {
        record["Residue_Position"]:
            record[
                "Minimum_Heavy_Atom_Distance_A"
            ]
        for record in wt_contacts
    }

    mutant_dict = {
        record["Residue_Position"]:
            record[
                "Minimum_Heavy_Atom_Distance_A"
            ]
        for record in mutant_contacts
    }

    all_positions = sorted(
        set(wt_dict)
        |
        set(mutant_dict)
    )

    records = []

    for position in all_positions:

        wt_present = (
            position in wt_dict
        )

        mutant_present = (
            position in mutant_dict
        )

        wt_distance = wt_dict.get(
            position,
            np.nan
        )

        mutant_distance = mutant_dict.get(
            position,
            np.nan
        )

        if (
            wt_present
            and mutant_present
        ):

            category = "Retained"

            change = (
                mutant_distance
                - wt_distance
            )

        elif wt_present:

            category = "Lost"

            change = np.nan

        else:

            category = "Gained"

            change = np.nan

        residue = (
            get_structure_residue(
                wt_chain,
                position
            )
            or
            get_structure_residue(
                mutant_chain,
                position
            )
        )

        records.append(
            {
                "Residue_Position":
                    position,

                "Residue_Name":
                    residue.resname,

                "Residue_AA":
                    safe_seq1(
                        residue.resname
                    ),

                "WT_Contact":
                    wt_present,

                "Mutant_Contact":
                    mutant_present,

                "WT_Min_Distance_A":
                    wt_distance,

                "Mutant_Min_Distance_A":
                    mutant_distance,

                "Distance_Change_A":
                    change,

                "Contact_Status":
                    category,
            }
        )

    return (
        records,
        wt_contacts,
        mutant_contacts
    )


def catalytic_distance(
    chain,
    candidate_position,
    catalytic_position
):

    candidate = get_structure_residue(
        chain,
        candidate_position
    )

    catalytic = get_structure_residue(
        chain,
        catalytic_position
    )

    if candidate is None:

        return np.nan

    if catalytic is None:

        return np.nan

    if candidate_position == catalytic_position:

        return 0.0

    return minimum_heavy_atom_distance(
        candidate,
        catalytic
    )


def get_polar_count(
    chain,
    target_position
):

    return len(
        candidate_polar_contacts(
            chain,
            target_position
        )
    )


def structural_impact_index(
    polar_contact_loss,
    lost_contacts,
    gained_contacts,
    catalytic_distance_change,
    local_ca_rmsd,
    physchem_score
):

    polar_component = min(
        max(
            polar_contact_loss,
            0
        ) * 2.0,
        10.0
    )

    lost_component = min(
        max(
            lost_contacts,
            0
        ) * 2.0,
        10.0
    )

    gained_component = min(
        max(
            gained_contacts,
            0
        ) * 1.0,
        5.0
    )

    catalytic_component = min(
        abs(
            catalytic_distance_change
        )
        if not np.isnan(
            catalytic_distance_change
        )
        else 0.0,
        5.0
    )

    local_rmsd_component = min(
        max(
            local_ca_rmsd,
            0
        )
        if not np.isnan(
            local_ca_rmsd
        )
        else 0.0,
        1.0
    ) * 5.0

    total = (
        polar_component
        + lost_component
        + gained_component
        + catalytic_component
        + local_rmsd_component
        + physchem_score
    )

    return {

        "Polar_Contact_Loss_Component":
            polar_component,

        "Lost_Contact_Component":
            lost_component,

        "Gained_Contact_Component":
            gained_component,

        "Catalytic_Distance_Component":
            catalytic_component,

        "Local_RMSD_Component":
            local_rmsd_component,

        "Physicochemical_Component":
            physchem_score,

        "Structural_Impact_Index":
            total,
    }


# =============================================================================
# START
# =============================================================================

section(
    "STEP 13 — COMPARATIVE STRUCTURAL ANALYSIS"
)

log(
    "Project:"
)

log(
    PROJECT_NAME
)

log(
    f"Project root: {PROJECT_ROOT}"
)

log(
    f"Step 13 output directory: {STEP13_DIR}"
)


# =============================================================================
# INPUT FILES
# =============================================================================

subsection(
    "CHECKING INPUT FILES"
)


candidate_files = list(
    PROJECT_ROOT.rglob(
        STEP9F_FILENAME
    )
)

if not candidate_files:

    status(
        "Step9F_exists",
        False,
        "Final Step 9F file not found"
    )

    sys.exit(1)

step9f_file = candidate_files[0]

status(
    "Step9F_exists",
    True,
    str(step9f_file)
)


wt_pdb_file = (
    STEP10_WT_DIR
    / WT_PDB_FILENAME
)

status(
    "Validated_WT_PDB_exists",
    wt_pdb_file.exists(),
    str(wt_pdb_file)
)

if not wt_pdb_file.exists():

    log(
        "ERROR: Step 10 validated WT PDB is missing."
    )

    sys.exit(1)


plddt_file = (
    STEP10_TABLE_DIR
    / STEP10_PLDDT_FILENAME
)

status(
    "Step10_pLDDT_exists",
    plddt_file.exists(),
    str(plddt_file)
)


# =============================================================================
# READ STEP 9F
# =============================================================================

subsection(
    "READING AUTHORITATIVE STEP 9F DATASET"
)

try:

    df = pd.read_csv(
        step9f_file,
        low_memory=False
    )

except Exception as exc:

    log(
        f"ERROR reading Step 9F: {exc}"
    )

    sys.exit(1)


log(
    f"Rows loaded    : {len(df)}"
)

log(
    f"Columns loaded : {len(df.columns)}"
)


required_columns = [

    "VariationID",
    "Protein_Change",
    "UniProt_ID",
    "Protein_Position",
    "Reference_Amino_Acid",
    "Alternate_Amino_Acid",
    "Structural_Analysis_Candidate",
    "Priority_Rank",
    "Final_Mutant_Rank",
    "Final_Mutant_Selection_Score",
    "Nearest_Catalytic_Residue",
    "Catalytic_Context",
]


missing_columns = [
    column
    for column in required_columns
    if column not in df.columns
]

status(
    "Step9F_required_columns",
    len(missing_columns) == 0,
    (
        "All required columns present"
        if not missing_columns
        else
        "Missing: "
        + ", ".join(
            missing_columns
        )
    )
)

if missing_columns:

    sys.exit(1)


status(
    "Step9F_expected_rows",
    len(df) == EXPECTED_VARIANTS,
    (
        f"Expected {EXPECTED_VARIANTS}, "
        f"observed {len(df)}"
    )
)

if len(df) != EXPECTED_VARIANTS:

    sys.exit(1)


# =============================================================================
# STRUCTURAL CANDIDATES
# =============================================================================

subsection(
    "IDENTIFYING THE 9 PRIORITIZED STRUCTURAL CANDIDATES"
)

structural_mask = (
    df[
        "Structural_Analysis_Candidate"
    ]
    .astype(str)
    .str.strip()
    .str.upper()
    .eq("YES")
)

structural_df = (
    df.loc[
        structural_mask
    ]
    .copy()
)

status(
    "Structural_candidate_count",
    len(structural_df)
    == EXPECTED_STRUCTURAL_CANDIDATES,
    (
        f"Expected {EXPECTED_STRUCTURAL_CANDIDATES}, "
        f"observed {len(structural_df)}"
    )
)

if len(structural_df) != EXPECTED_STRUCTURAL_CANDIDATES:

    sys.exit(1)


# Sort according to Step 9F final mutant rank.
structural_df[
    "_sort_rank"
] = pd.to_numeric(
    structural_df[
        "Final_Mutant_Rank"
    ],
    errors="coerce"
)

structural_df = (
    structural_df
    .sort_values(
        [
            "_sort_rank",
            "Priority_Rank",
        ],
        na_position="last"
    )
    .reset_index(
        drop=True
    )
)

structural_df.drop(
    columns=["_sort_rank"],
    inplace=True
)


log("")
log(
    "Selected candidates:"
)

for index, row in structural_df.iterrows():

    log(
        f"{index + 1:2d}. "
        f"{row['Protein_Change']:<16} "
        f"VariationID="
        f"{int(float(row['VariationID'])):<10} "
        f"Position="
        f"{int(float(row['Protein_Position']))}"
    )


expected_protein_changes = {
    "p.Asp166Val",
    "p.Gly49Trp",
    "p.Cys28Arg",
    "p.Tyr21Cys",
    "p.Pro186Ser",
    "p.Arg247Thr",
    "p.Leu142Phe",
    "p.Pro186His",
    "p.Leu51Ser",
}

observed_changes = set(
    structural_df[
        "Protein_Change"
    ]
    .astype(str)
)

status(
    "Expected_nine_variants",
    observed_changes
    == expected_protein_changes,
    "All expected structural candidates present"
    if observed_changes == expected_protein_changes
    else
    (
        "Observed mismatch: "
        + str(
            sorted(
                observed_changes
                ^
                expected_protein_changes
            )
        )
    )
)

if observed_changes != expected_protein_changes:

    sys.exit(1)


# =============================================================================
# PYMOL INITIALIZATION
# =============================================================================

subsection(
    "INITIALIZING PYMOL"
)

try:

    pymol_version = (
        cmd.get_version()[0]
    )

    status(
        "PyMOL_import",
        True,
        f"PyMOL {pymol_version}"
    )

except Exception as exc:

    status(
        "PyMOL_import",
        False,
        str(exc)
    )

    sys.exit(1)


# =============================================================================
# pLDDT INFORMATION
# =============================================================================

subsection(
    "LOADING LOCAL pLDDT INFORMATION"
)

plddt_external = {}

if plddt_file.exists():

    try:

        plddt_df = pd.read_csv(
            plddt_file
        )

        log(
            f"pLDDT rows loaded: "
            f"{len(plddt_df)}"
        )

        if "Position" in plddt_df.columns:

            status(
                "pLDDT_residue_column",
                True,
                "Position"
            )

        else:

            status(
                "pLDDT_residue_column",
                False
            )

        if "pLDDT" in plddt_df.columns:

            status(
                "pLDDT_value_column",
                True,
                "pLDDT"
            )

        else:

            status(
                "pLDDT_value_column",
                False
            )

        if (
            "Position" in plddt_df.columns
            and
            "pLDDT" in plddt_df.columns
        ):

            for _, row in plddt_df.iterrows():

                try:

                    position = int(
                        float(
                            row["Position"]
                        )
                    )

                    value = float(
                        row["pLDDT"]
                    )

                    plddt_external[
                        position
                    ] = value

                except Exception:

                    continue

    except Exception as exc:

        log(
            f"WARNING: Could not read Step 10 pLDDT table: {exc}"
        )

else:

    log(
        "Step 10 pLDDT table unavailable."
    )

    log(
        "pLDDT will be extracted from WT PDB B-factors."
    )


# =============================================================================
# LOAD WT
# =============================================================================

subsection(
    "LOADING VALIDATED STEP 10 WT STRUCTURE"
)

wt_structure = load_structure(
    wt_pdb_file,
    "PNPLA3_WT"
)

wt_chain = get_chain(
    wt_structure,
    "A"
)

if wt_chain is None:

    log(
        "ERROR: WT chain A not found."
    )

    sys.exit(1)

wt_residues = get_protein_residues(
    wt_chain
)

wt_positions = sorted(
    residue_number(
        residue
    )
    for residue in wt_residues
)

status(
    "WT_protein_chain",
    len(wt_residues) > 0,
    (
        f"{len(wt_residues)} protein residues"
    )
)


# =============================================================================
# VALIDATE ALL STEP 9F CANDIDATES AGAINST WT
# =============================================================================

subsection(
    "VALIDATING ALL 9 CANDIDATES AGAINST WT STRUCTURE"
)

candidate_validation_records = []

for _, row in structural_df.iterrows():

    protein_change = str(
        row["Protein_Change"]
    ).strip()

    variation_id = int(
        float(
            row["VariationID"]
        )
    )

    position = int(
        float(
            row["Protein_Position"]
        )
    )

    wt_expected = (
        str(
            row["Reference_Amino_Acid"]
        )
        .strip()
        .upper()
    )

    mut_expected = (
        str(
            row["Alternate_Amino_Acid"]
        )
        .strip()
        .upper()
    )

    if len(wt_expected) != 1:

        wt_expected = safe_seq1(
            wt_expected
        )

    if len(mut_expected) != 1:

        mut_expected = safe_seq1(
            mut_expected
        )

    wt_residue = get_structure_residue(
        wt_chain,
        position
    )

    observed_wt = (
        safe_seq1(
            wt_residue.resname
        )
        if wt_residue is not None
        else None
    )

    passed = (
        wt_residue is not None
        and observed_wt == wt_expected
        and mut_expected in AA1_TO_AA3
    )

    status(
        f"{protein_change}_WT_residue",
        passed,
        (
            f"Expected {wt_expected}, "
            f"observed {observed_wt}"
        )
    )

    candidate_validation_records.append(
        {
            "VariationID":
                variation_id,

            "Protein_Change":
                protein_change,

            "Protein_Position":
                position,

            "Expected_WT":
                wt_expected,

            "Observed_WT":
                observed_wt,

            "Expected_Mutant":
                mut_expected,

            "WT_Validation":
                passed,
        }
    )

    if not passed:

        log(
            f"ERROR: WT validation failed for "
            f"{protein_change}."
        )

        sys.exit(1)


# =============================================================================
# MUTANT GENERATION
# =============================================================================

subsection(
    "GENERATING TRUE PyMOL SIDE-CHAIN-REMODELED MUTANTS"
)

mutation_validation_records = []

mutant_paths = {}

for index, row in structural_df.iterrows():

    protein_change = str(
        row["Protein_Change"]
    ).strip()

    variation_id = int(
        float(
            row["VariationID"]
        )
    )

    position = int(
        float(
            row["Protein_Position"]
        )
    )

    wt_one = (
        str(
            row["Reference_Amino_Acid"]
        )
        .strip()
        .upper()
    )

    mut_one = (
        str(
            row["Alternate_Amino_Acid"]
        )
        .strip()
        .upper()
    )

    if len(wt_one) != 1:

        wt_one = safe_seq1(
            wt_one
        )

    if len(mut_one) != 1:

        mut_one = safe_seq1(
            mut_one
        )

    mut_three = AA1_TO_AA3[
        mut_one
    ]

    subsection(
        f"CANDIDATE {index + 1}/9: "
        f"{protein_change}"
    )

    log(
        f"VariationID      : {variation_id}"
    )

    log(
        f"Protein position : {position}"
    )

    log(
        f"Expected WT      : {wt_one}"
    )

    log(
        f"Expected mutant  : {mut_one}"
    )

    safe_name = (
        protein_change
        .replace(
            "p.",
            ""
        )
        .replace(
            ">",
            "_"
        )
    )

    mutant_pdb = (
        STEP13_MUTANT_DIR
        / (
            f"PNPLA3_{safe_name}_"
            f"{variation_id}_mutant.pdb"
        )
    )

    try:

        generate_mutant_with_pymol(
            wt_pdb=wt_pdb_file,
            mutant_pdb=mutant_pdb,
            position=position,
            mutant_three=mut_three,
            mutant_one=mut_one,
            chain_id="A"
        )

    except Exception as exc:

        status(
            f"{protein_change}_mutant_generation",
            False,
            str(exc)
        )

        log(
            "ERROR: Mutant generation stopped."
        )

        log(
            f"Candidate: {protein_change}"
        )

        log(
            f"Expected mutant: {mut_three}"
        )

        sys.exit(1)

    generated = mutant_pdb.exists()

    status(
        f"{protein_change}_mutant_PDB",
        generated,
        str(mutant_pdb)
    )

    if not generated:

        sys.exit(1)

    validation = validate_mutant_structure(
        mutant_pdb,
        position,
        mut_one,
        mut_three
    )

    status(
        f"{protein_change}_mutant_validation",
        validation["passed"],
        (
            f"Observed "
            f"{validation.get('observed_three', 'NA')} "
            f"({validation.get('observed_one', 'NA')})"
        )
    )

    if not validation["passed"]:

        log(
            f"ERROR: Mutant validation failed for "
            f"{protein_change}."
        )

        sys.exit(1)

    mutation_validation_records.append(
        {
            "VariationID":
                variation_id,

            "Protein_Change":
                protein_change,

            "Protein_Position":
                position,

            "WT_Amino_Acid":
                wt_one,

            "Mutant_Amino_Acid":
                mut_one,

            "Mutant_Three_Letter":
                mut_three,

            "Mutant_PDB":
                str(mutant_pdb),

            "Mutant_Residue_Validated":
                True,

            "Sidechain_Atoms_Validated":
                validation[
                    "sidechain_atoms_present"
                ],

            "Mutation_Method":
                "PyMOL mutagenesis wizard",
        }
    )

    mutant_paths[
        protein_change
    ] = mutant_pdb


# =============================================================================
# COPY WT REFERENCE INTO STEP 13
# =============================================================================

wt_reference_copy = (
    STEP13_WT_DIR
    / "PNPLA3_WT_reference.pdb"
)

shutil.copy2(
    wt_pdb_file,
    wt_reference_copy
)


# =============================================================================
# COMPARATIVE ANALYSIS
# =============================================================================

subsection(
    "COMPARATIVE STRUCTURAL ANALYSIS OF ALL 9 VARIANTS"
)

comparison_records = []

contact_records_all = []

polar_records_all = []

local_distance_records_all = []

local_rmsd_records_all = []

pLDDT_records_all = []


for index, row in structural_df.iterrows():

    protein_change = str(
        row["Protein_Change"]
    ).strip()

    variation_id = int(
        float(
            row["VariationID"]
        )
    )

    position = int(
        float(
            row["Protein_Position"]
        )
    )

    wt_one = (
        str(
            row["Reference_Amino_Acid"]
        )
        .strip()
        .upper()
    )

    mut_one = (
        str(
            row["Alternate_Amino_Acid"]
        )
        .strip()
        .upper()
    )

    if len(wt_one) != 1:

        wt_one = safe_seq1(
            wt_one
        )

    if len(mut_one) != 1:

        mut_one = safe_seq1(
            mut_one
        )

    mutant_pdb = mutant_paths[
        protein_change
    ]

    mutant_structure = load_structure(
        mutant_pdb,
        f"MUTANT_{variation_id}"
    )

    mutant_chain = get_chain(
        mutant_structure,
        "A"
    )

    if mutant_chain is None:

        log(
            f"ERROR: Mutant chain missing for "
            f"{protein_change}"
        )

        sys.exit(1)

    # -------------------------------------------------------------------------
    # WT / mutant target residue validation
    # -------------------------------------------------------------------------

    wt_target = get_structure_residue(
        wt_chain,
        position
    )

    mutant_target = get_structure_residue(
        mutant_chain,
        position
    )

    wt_observed = (
        safe_seq1(
            wt_target.resname
        )
        if wt_target is not None
        else None
    )

    mutant_observed = (
        safe_seq1(
            mutant_target.resname
        )
        if mutant_target is not None
        else None
    )

    if wt_observed != wt_one:

        log(
            f"ERROR: WT mismatch for {protein_change}"
        )

        sys.exit(1)

    if mutant_observed != mut_one:

        log(
            f"ERROR: mutant mismatch for {protein_change}"
        )

        sys.exit(1)

    # -------------------------------------------------------------------------
    # Global RMSD
    # -------------------------------------------------------------------------

    global_metrics = calculate_structural_comparison(
        wt_structure,
        mutant_structure,
        "A"
    )

    global_ca_rmsd = (
        global_metrics[
            "global_ca_rmsd"
        ]
    )

    global_backbone_rmsd = (
        global_metrics[
            "global_backbone_rmsd"
        ]
    )

    # -------------------------------------------------------------------------
    # Local RMSD
    # -------------------------------------------------------------------------

    local_ca_rmsd = calculate_local_rmsd(
        wt_chain,
        mutant_chain,
        position,
        LOCAL_RMSD_WINDOW
    )

    # -------------------------------------------------------------------------
    # Contact comparison
    # -------------------------------------------------------------------------

    (
        contact_records,
        wt_contacts,
        mutant_contacts
    ) = contact_comparison(
        wt_chain,
        mutant_chain,
        position
    )

    for record in contact_records:

        contact_records_all.append(
            {
                "VariationID":
                    variation_id,

                "Protein_Change":
                    protein_change,

                **record,
            }
        )

    retained_contacts = [
        record
        for record in contact_records
        if record[
            "Contact_Status"
        ]
        == "Retained"
    ]

    lost_contacts = [
        record
        for record in contact_records
        if record[
            "Contact_Status"
        ]
        == "Lost"
    ]

    gained_contacts = [
        record
        for record in contact_records
        if record[
            "Contact_Status"
        ]
        == "Gained"
    ]

    # -------------------------------------------------------------------------
    # Polar contacts
    # -------------------------------------------------------------------------

    wt_polar = candidate_polar_contacts(
        wt_chain,
        position
    )

    mutant_polar = candidate_polar_contacts(
        mutant_chain,
        position
    )

    for record in wt_polar:

        polar_records_all.append(
            {
                "VariationID":
                    variation_id,

                "Protein_Change":
                    protein_change,

                "Structure":
                    "WT",

                **record,
            }
        )

    for record in mutant_polar:

        polar_records_all.append(
            {
                "VariationID":
                    variation_id,

                "Protein_Change":
                    protein_change,

                "Structure":
                    "Mutant",

                **record,
            }
        )

    polar_loss = (
        len(wt_polar)
        -
        len(mutant_polar)
    )

    # -------------------------------------------------------------------------
    # Catalytic context
    # -------------------------------------------------------------------------

    catalytic_position = parse_catalytic_position(
        row[
            "Nearest_Catalytic_Residue"
        ]
    )

    if np.isnan(
        catalytic_position
    ):

        catalytic_position = np.nan

        wt_catalytic_distance = np.nan

        mutant_catalytic_distance = np.nan

        catalytic_distance_change = np.nan

    else:

        catalytic_position = int(
            catalytic_position
        )

        wt_catalytic_distance = catalytic_distance(
            wt_chain,
            position,
            catalytic_position
        )

        mutant_catalytic_distance = catalytic_distance(
            mutant_chain,
            position,
            catalytic_position
        )

        if (
            np.isnan(
                wt_catalytic_distance
            )
            or
            np.isnan(
                mutant_catalytic_distance
            )
        ):

            catalytic_distance_change = np.nan

        else:

            catalytic_distance_change = (
                mutant_catalytic_distance
                -
                wt_catalytic_distance
            )

    # -------------------------------------------------------------------------
    # Local environment
    # -------------------------------------------------------------------------

    wt_local = build_local_environment(
        wt_chain,
        position
    )

    mutant_local = build_local_environment(
        mutant_chain,
        position
    )

    wt_local_dict = {
        record[
            "Residue_Position"
        ]:
        record[
            "Minimum_Heavy_Atom_Distance_A"
        ]
        for record in wt_local
    }

    mutant_local_dict = {
        record[
            "Residue_Position"
        ]:
        record[
            "Minimum_Heavy_Atom_Distance_A"
        ]
        for record in mutant_local
    }

    all_local_positions = sorted(
        set(wt_local_dict)
        |
        set(mutant_local_dict)
    )

    for local_position in all_local_positions:

        wt_distance = wt_local_dict.get(
            local_position,
            np.nan
        )

        mutant_distance = mutant_local_dict.get(
            local_position,
            np.nan
        )

        if (
            not np.isnan(
                wt_distance
            )
            and
            not np.isnan(
                mutant_distance
            )
        ):

            distance_change = (
                mutant_distance
                -
                wt_distance
            )

        else:

            distance_change = np.nan

        residue = (
            get_structure_residue(
                wt_chain,
                local_position
            )
            or
            get_structure_residue(
                mutant_chain,
                local_position
            )
        )

        local_distance_records_all.append(
            {
                "VariationID":
                    variation_id,

                "Protein_Change":
                    protein_change,

                "Target_Position":
                    position,

                "Residue_Position":
                    local_position,

                "Relative_Position":
                    local_position - position,

                "Residue_Name":
                    residue.resname,

                "Residue_AA":
                    safe_seq1(
                        residue.resname
                    ),

                "WT_Distance_A":
                    wt_distance,

                "Mutant_Distance_A":
                    mutant_distance,

                "Distance_Change_A":
                    distance_change,
            }
        )

    # -------------------------------------------------------------------------
    # Local CA RMSD profile
    # -------------------------------------------------------------------------

    local_profile = build_local_ca_rmsd_profile(
        wt_chain,
        mutant_chain,
        position,
        LOCAL_RMSD_WINDOW
    )

    for record in local_profile:

        local_rmsd_records_all.append(
            {
                "VariationID":
                    variation_id,

                "Protein_Change":
                    protein_change,

                **record,
            }
        )

    # -------------------------------------------------------------------------
    # Candidate pLDDT
    # -------------------------------------------------------------------------

    if position in plddt_external:

        candidate_plddt = (
            plddt_external[
                position
            ]
        )

        plddt_source = (
            "Step10_Table_S10_10"
        )

    else:

        candidate_plddt = get_residue_plddt(
            wt_target
        )

        plddt_source = (
            "Step10_WT_PDB_B_factor"
        )

    pLDDT_records_all.append(
        {
            "VariationID":
                variation_id,

            "Protein_Change":
                protein_change,

            "Protein_Position":
                position,

            "WT_Amino_Acid":
                wt_one,

            "pLDDT":
                candidate_plddt,

            "pLDDT_Source":
                plddt_source,
        }
    )

    # -------------------------------------------------------------------------
    # Physicochemical impact
    # -------------------------------------------------------------------------

    physchem_score = physicochemical_impact(
        wt_one,
        mut_one
    )

    # -------------------------------------------------------------------------
    # Structural impact index
    # -------------------------------------------------------------------------

    impact = structural_impact_index(
        polar_contact_loss=polar_loss,
        lost_contacts=len(
            lost_contacts
        ),
        gained_contacts=len(
            gained_contacts
        ),
        catalytic_distance_change=
            catalytic_distance_change,
        local_ca_rmsd=local_ca_rmsd,
        physchem_score=physchem_score
    )

    # -------------------------------------------------------------------------
    # Log results
    # -------------------------------------------------------------------------

    log("")

    log(
        f"{protein_change}"
    )

    log(
        f"  Global Cα RMSD       : "
        f"{global_ca_rmsd:.4f} Å"
    )

    log(
        f"  Global backbone RMSD : "
        f"{global_backbone_rmsd:.4f} Å"
    )

    log(
        f"  Local Cα RMSD        : "
        f"{local_ca_rmsd:.4f} Å"
    )

    log(
        f"  WT contacts          : "
        f"{len(wt_contacts)}"
    )

    log(
        f"  Mutant contacts      : "
        f"{len(mutant_contacts)}"
    )

    log(
        f"  Contacts retained    : "
        f"{len(retained_contacts)}"
    )

    log(
        f"  Contacts lost        : "
        f"{len(lost_contacts)}"
    )

    log(
        f"  Contacts gained      : "
        f"{len(gained_contacts)}"
    )

    log(
        f"  WT polar contacts    : "
        f"{len(wt_polar)}"
    )

    log(
        f"  Mutant polar contacts: "
        f"{len(mutant_polar)}"
    )

    log(
        f"  Candidate pLDDT      : "
        f"{candidate_plddt:.2f}"
    )

    if not np.isnan(
        catalytic_position
    ):

        log(
            f"  Catalytic residue    : "
            f"{int(catalytic_position)}"
        )

        log(
            f"  WT catalytic dist.   : "
            f"{wt_catalytic_distance:.3f} Å"
        )

        log(
            f"  Mutant catalytic dist.: "
            f"{mutant_catalytic_distance:.3f} Å"
        )

        log(
            f"  Catalytic Δdistance  : "
            f"{catalytic_distance_change:+.3f} Å"
        )

    log(
        f"  Structural impact    : "
        f"{impact['Structural_Impact_Index']:.3f}"
    )

    # -------------------------------------------------------------------------
    # Main record
    # -------------------------------------------------------------------------

    comparison_records.append(
        {
            "VariationID":
                variation_id,

            "Protein_Change":
                protein_change,

            "Protein_Position":
                position,

            "WT_Amino_Acid":
                wt_one,

            "Mutant_Amino_Acid":
                mut_one,

            "Catalytic_Context":
                row[
                    "Catalytic_Context"
                ],

            "Nearest_Catalytic_Residue":
                row[
                    "Nearest_Catalytic_Residue"
                ],

            "Nearest_Catalytic_Position":
                catalytic_position,

            "WT_Catalytic_Distance_A":
                wt_catalytic_distance,

            "Mutant_Catalytic_Distance_A":
                mutant_catalytic_distance,

            "Catalytic_Distance_Change_A":
                catalytic_distance_change,

            "WT_Contact_Count":
                len(wt_contacts),

            "Mutant_Contact_Count":
                len(mutant_contacts),

            "Contacts_Retained":
                len(retained_contacts),

            "Contacts_Lost":
                len(lost_contacts),

            "Contacts_Gained":
                len(gained_contacts),

            "WT_Polar_Contact_Count":
                len(wt_polar),

            "Mutant_Polar_Contact_Count":
                len(mutant_polar),

            "Polar_Contact_Change":
                len(mutant_polar)
                -
                len(wt_polar),

            "Global_CA_RMSD_A":
                global_ca_rmsd,

            "Global_Backbone_RMSD_A":
                global_backbone_rmsd,

            "Local_CA_RMSD_A":
                local_ca_rmsd,

            "Candidate_pLDDT":
                candidate_plddt,

            "pLDDT_Source":
                plddt_source,

            "Physicochemical_Impact_Score":
                physchem_score,

            **impact,

            "Mutation_Model_Method":
                "PyMOL mutagenesis wizard",

            "Structural_Model_Type":
                "AlphaFold WT + PyMOL side-chain remodeled mutant",

            "Energy_Minimization_Performed":
                False,

            "Molecular_Dynamics_Performed":
                False,
        }
    )


# =============================================================================
# DATAFRAMES
# =============================================================================

comparison_df = pd.DataFrame(
    comparison_records
)

contact_df = pd.DataFrame(
    contact_records_all
)

polar_df = pd.DataFrame(
    polar_records_all
)

local_distance_df = pd.DataFrame(
    local_distance_records_all
)

local_rmsd_df = pd.DataFrame(
    local_rmsd_records_all
)

plddt_all_df = pd.DataFrame(
    pLDDT_records_all
)

candidate_validation_df = pd.DataFrame(
    candidate_validation_records
)

mutation_validation_df = pd.DataFrame(
    mutation_validation_records
)


# =============================================================================
# TABLE 1 — ALL 9 STRUCTURAL COMPARISON
# =============================================================================

table1 = (
    TABLE_DIR
    / "Table_S13_1_all9_structural_comparison.csv"
)

comparison_df.to_csv(
    table1,
    index=False
)


# =============================================================================
# TABLE 2 — HEAVY ATOM CONTACTS
# =============================================================================

table2 = (
    TABLE_DIR
    / "Table_S13_2_all9_heavy_atom_contacts.csv"
)

contact_df.to_csv(
    table2,
    index=False
)


# =============================================================================
# TABLE 3 — POLAR CONTACTS
# =============================================================================

table3 = (
    TABLE_DIR
    / "Table_S13_3_all9_candidate_polar_contacts.csv"
)

polar_df.to_csv(
    table3,
    index=False
)


# =============================================================================
# TABLE 4 — LOCAL DISTANCE PROFILES
# =============================================================================

table4 = (
    TABLE_DIR
    / "Table_S13_4_all9_local_distance_profiles.csv"
)

local_distance_df.to_csv(
    table4,
    index=False
)


# =============================================================================
# TABLE 5 — LOCAL RMSD AND pLDDT
# =============================================================================

table5 = (
    TABLE_DIR
    / "Table_S13_5_all9_local_RMSD_and_pLDDT.csv"
)

table5_records = []

for _, row in comparison_df.iterrows():

    position = int(
        row["Protein_Position"]
    )

    plddt_row = plddt_all_df.loc[
        plddt_all_df[
            "VariationID"
        ]
        ==
        row["VariationID"]
    ]

    candidate_plddt = (
        plddt_row.iloc[0]["pLDDT"]
        if not plddt_row.empty
        else np.nan
    )

    table5_records.append(
        {
            "VariationID":
                row["VariationID"],

            "Protein_Change":
                row["Protein_Change"],

            "Protein_Position":
                position,

            "Global_CA_RMSD_A":
                row[
                    "Global_CA_RMSD_A"
                ],

            "Global_Backbone_RMSD_A":
                row[
                    "Global_Backbone_RMSD_A"
                ],

            "Local_CA_RMSD_A":
                row[
                    "Local_CA_RMSD_A"
                ],

            "Candidate_pLDDT":
                candidate_plddt,
        }
    )

table5_df = pd.DataFrame(
    table5_records
)

table5_df.to_csv(
    table5,
    index=False
)


# =============================================================================
# TABLE 6 — FINAL STRUCTURAL RANKING
# =============================================================================

subsection(
    "FINAL COMPARATIVE STRUCTURAL RANKING"
)

ranking_df = comparison_df.copy()

ranking_df = ranking_df.sort_values(
    [
        "Structural_Impact_Index",
        "Polar_Contact_Change",
        "Contacts_Lost",
        "Catalytic_Distance_Change_A",
        "Physicochemical_Impact_Score",
    ],
    ascending=[
        False,
        True,
        False,
        False,
        False,
    ],
    na_position="last"
).reset_index(
    drop=True
)

ranking_df[
    "Structural_Impact_Rank"
] = np.arange(
    1,
    len(ranking_df) + 1
)

ranking_columns = [

    "Structural_Impact_Rank",

    "VariationID",

    "Protein_Change",

    "Protein_Position",

    "WT_Amino_Acid",

    "Mutant_Amino_Acid",

    "Structural_Impact_Index",

    "Polar_Contact_Loss_Component",

    "Lost_Contact_Component",

    "Gained_Contact_Component",

    "Catalytic_Distance_Component",

    "Local_RMSD_Component",

    "Physicochemical_Component",

    "Global_CA_RMSD_A",

    "Global_Backbone_RMSD_A",

    "Local_CA_RMSD_A",

    "WT_Contact_Count",

    "Mutant_Contact_Count",

    "Contacts_Retained",

    "Contacts_Lost",

    "Contacts_Gained",

    "WT_Polar_Contact_Count",

    "Mutant_Polar_Contact_Count",

    "Polar_Contact_Change",

    "Nearest_Catalytic_Residue",

    "WT_Catalytic_Distance_A",

    "Mutant_Catalytic_Distance_A",

    "Catalytic_Distance_Change_A",

    "Candidate_pLDDT",

    "Physicochemical_Impact_Score",
]


ranking_columns = [
    column
    for column in ranking_columns
    if column in ranking_df.columns
]

ranking_output = ranking_df[
    ranking_columns
].copy()

table6 = (
    TABLE_DIR
    / "Table_S13_6_final_structural_ranking.csv"
)

ranking_output.to_csv(
    table6,
    index=False
)


log("")

for _, row in ranking_output.iterrows():

    log(
        f"Rank {int(row['Structural_Impact_Rank']):2d} "
        f"{row['Protein_Change']:<16} "
        f"Impact="
        f"{row['Structural_Impact_Index']:.3f}"
    )


# =============================================================================
# TABLE 7 — MUTATION VALIDATION
# =============================================================================

table7 = (
    TABLE_DIR
    / "Table_S13_7_mutant_validation.csv"
)

mutation_validation_df.to_csv(
    table7,
    index=False
)


# =============================================================================
# TABLE 8 — CANDIDATE VALIDATION
# =============================================================================

table8 = (
    TABLE_DIR
    / "Table_S13_8_candidate_WT_validation.csv"
)

candidate_validation_df.to_csv(
    table8,
    index=False
)


# =============================================================================
# FIGURES
# =============================================================================

subsection(
    "GENERATING COMPARATIVE STRUCTURAL FIGURES"
)


# =============================================================================
# FIGURE 1 — STRUCTURAL IMPACT RANKING
# =============================================================================

figure1 = (
    FIGURE_DIR
    / "Figure_S13_1_comparative_structural_impact_ranking.png"
)

plot_df = ranking_output.sort_values(
    "Structural_Impact_Rank"
)

plt.figure(
    figsize=(10, 7),
    dpi=300
)

plt.bar(
    plot_df[
        "Protein_Change"
    ],
    plot_df[
        "Structural_Impact_Index"
    ]
)

plt.xlabel(
    "PNPLA3 variant"
)

plt.ylabel(
    "Comparative structural impact index"
)

plt.title(
    "Comparative Structural Impact of 9 Prioritized PNPLA3 Variants"
)

plt.xticks(
    rotation=45,
    ha="right"
)

plt.tight_layout()

plt.savefig(
    figure1,
    dpi=300,
    bbox_inches="tight"
)

plt.close()


# =============================================================================
# FIGURE 2 — LOCAL CA RMSD
# =============================================================================

figure2 = (
    FIGURE_DIR
    / "Figure_S13_2_local_CA_RMSD_comparison.png"
)

rmsd_plot_df = comparison_df.copy()

plt.figure(
    figsize=(10, 7),
    dpi=300
)

plt.bar(
    rmsd_plot_df[
        "Protein_Change"
    ],
    rmsd_plot_df[
        "Local_CA_RMSD_A"
    ]
)

plt.xlabel(
    "PNPLA3 variant"
)

plt.ylabel(
    "Local Cα RMSD (Å)"
)

plt.title(
    "Local Structural Displacement Around Prioritized Variants"
)

plt.xticks(
    rotation=45,
    ha="right"
)

plt.tight_layout()

plt.savefig(
    figure2,
    dpi=300,
    bbox_inches="tight"
)

plt.close()


# =============================================================================
# FIGURE 3 — POLAR CONTACTS
# =============================================================================

figure3 = (
    FIGURE_DIR
    / "Figure_S13_3_polar_contact_comparison.png"
)

polar_plot = comparison_df.copy()

x = np.arange(
    len(polar_plot)
)

width = 0.36

plt.figure(
    figsize=(11, 7),
    dpi=300
)

plt.bar(
    x - width / 2,
    polar_plot[
        "WT_Polar_Contact_Count"
    ],
    width,
    label="WT"
)

plt.bar(
    x + width / 2,
    polar_plot[
        "Mutant_Polar_Contact_Count"
    ],
    width,
    label="Mutant"
)

plt.xticks(
    x,
    polar_plot[
        "Protein_Change"
    ],
    rotation=45,
    ha="right"
)

plt.xlabel(
    "PNPLA3 variant"
)

plt.ylabel(
    "Candidate polar heavy-atom contacts"
)

plt.title(
    "WT vs Mutant Candidate Polar Contacts"
)

plt.legend()

plt.tight_layout()

plt.savefig(
    figure3,
    dpi=300,
    bbox_inches="tight"
)

plt.close()


# =============================================================================
# FIGURE 4 — CONTACT CHANGES
# =============================================================================

figure4 = (
    FIGURE_DIR
    / "Figure_S13_4_contact_changes_comparison.png"
)

contact_plot = comparison_df.copy()

plt.figure(
    figsize=(11, 7),
    dpi=300
)

x = np.arange(
    len(contact_plot)
)

width = 0.25

plt.bar(
    x - width,
    contact_plot[
        "Contacts_Retained"
    ],
    width,
    label="Retained"
)

plt.bar(
    x,
    contact_plot[
        "Contacts_Lost"
    ],
    width,
    label="Lost"
)

plt.bar(
    x + width,
    contact_plot[
        "Contacts_Gained"
    ],
    width,
    label="Gained"
)

plt.xticks(
    x,
    contact_plot[
        "Protein_Change"
    ],
    rotation=45,
    ha="right"
)

plt.xlabel(
    "PNPLA3 variant"
)

plt.ylabel(
    "Number of residue contacts"
)

plt.title(
    "Comparative Heavy-Atom Contact Changes"
)

plt.legend()

plt.tight_layout()

plt.savefig(
    figure4,
    dpi=300,
    bbox_inches="tight"
)

plt.close()


# =============================================================================
# FIGURE 5 — pLDDT
# =============================================================================

figure5 = (
    FIGURE_DIR
    / "Figure_S13_5_variant_residue_pLDDT.png"
)

plt.figure(
    figsize=(10, 7),
    dpi=300
)

plt.bar(
    plddt_all_df[
        "Protein_Change"
    ],
    plddt_all_df[
        "pLDDT"
    ]
)

plt.xlabel(
    "PNPLA3 variant"
)

plt.ylabel(
    "Residue pLDDT"
)

plt.ylim(
    0,
    100
)

plt.title(
    "AlphaFold Confidence at the Nine Prioritized Variant Residues"
)

plt.xticks(
    rotation=45,
    ha="right"
)

plt.tight_layout()

plt.savefig(
    figure5,
    dpi=300,
    bbox_inches="tight"
)

plt.close()


# =============================================================================
# FIGURE 6 — CATALYTIC DISTANCE
# =============================================================================

figure6 = (
    FIGURE_DIR
    / "Figure_S13_6_catalytic_context_distance_comparison.png"
)

catalytic_plot = comparison_df[
    [
        "Protein_Change",
        "WT_Catalytic_Distance_A",
        "Mutant_Catalytic_Distance_A",
    ]
].copy()

x = np.arange(
    len(catalytic_plot)
)

width = 0.36

plt.figure(
    figsize=(11, 7),
    dpi=300
)

plt.bar(
    x - width / 2,
    catalytic_plot[
        "WT_Catalytic_Distance_A"
    ],
    width,
    label="WT"
)

plt.bar(
    x + width / 2,
    catalytic_plot[
        "Mutant_Catalytic_Distance_A"
    ],
    width,
    label="Mutant"
)

plt.xticks(
    x,
    catalytic_plot[
        "Protein_Change"
    ],
    rotation=45,
    ha="right"
)

plt.xlabel(
    "PNPLA3 variant"
)

plt.ylabel(
    "Minimum heavy-atom distance to nearest catalytic residue (Å)"
)

plt.title(
    "Comparative Catalytic-Context Distances"
)

plt.legend()

plt.tight_layout()

plt.savefig(
    figure6,
    dpi=300,
    bbox_inches="tight"
)

plt.close()


# =============================================================================
# FIGURE 7 — PHYSICOCHEMICAL IMPACT
# =============================================================================

figure7 = (
    FIGURE_DIR
    / "Figure_S13_7_physicochemical_impact_comparison.png"
)

plt.figure(
    figsize=(10, 7),
    dpi=300
)

plt.bar(
    comparison_df[
        "Protein_Change"
    ],
    comparison_df[
        "Physicochemical_Impact_Score"
    ]
)

plt.xlabel(
    "PNPLA3 variant"
)

plt.ylabel(
    "Physicochemical impact score"
)

plt.title(
    "Comparative Physicochemical Impact of Prioritized Variants"
)

plt.xticks(
    rotation=45,
    ha="right"
)

plt.tight_layout()

plt.savefig(
    figure7,
    dpi=300,
    bbox_inches="tight"
)

plt.close()


# =============================================================================
# PYMoL 3D FIGURES FOR ALL 9
# =============================================================================

subsection(
    "GENERATING PyMOL 3D STRUCTURAL FIGURES"
)

PYMOL_3D_DIR = (
    FIGURE_DIR
    / "PyMOL_3D"
)

PYMOL_3D_DIR.mkdir(
    parents=True,
    exist_ok=True
)


pymol_figure_records = []


for _, row in structural_df.iterrows():

    protein_change = str(
        row["Protein_Change"]
    ).strip()

    position = int(
        float(
            row["Protein_Position"]
        )
    )

    mutant_pdb = mutant_paths[
        protein_change
    ]

    safe_name = (
        protein_change
        .replace(
            "p.",
            ""
        )
    )

    output_png = (
        PYMOL_3D_DIR
        / (
            f"Figure_S13_"
            f"{safe_name}_3D.png"
        )
    )

    try:

        cmd.reinitialize()

        cmd.bg_color(
            "white"
        )

        cmd.load(
            str(wt_pdb_file),
            "WT"
        )

        cmd.load(
            str(mutant_pdb),
            "MUTANT"
        )

        cmd.hide(
            "everything",
            "WT MUTANT"
        )

        cmd.show(
            "cartoon",
            "WT"
        )

        cmd.show(
            "cartoon",
            "MUTANT"
        )

        cmd.color(
            "cyan",
            "WT"
        )

        cmd.color(
            "green",
            "MUTANT"
        )

        wt_selection = (
            f"WT and chain A and resi {position}"
        )

        mutant_selection = (
            f"MUTANT and chain A and resi {position}"
        )

        cmd.show(
            "sticks",
            wt_selection
        )

        cmd.show(
            "sticks",
            mutant_selection
        )

        cmd.color(
            "red",
            wt_selection
        )

        cmd.color(
            "yellow",
            mutant_selection
        )

        cmd.zoom(
            (
                f"(WT or MUTANT) "
                f"and chain A "
                f"and resi {position}"
            ),
            10
        )

        cmd.png(
            str(output_png),
            width=2000,
            height=1500,
            dpi=300,
            ray=1
        )

        pymol_figure_records.append(
            {
                "Protein_Change":
                    protein_change,

                "Position":
                    position,

                "Figure":
                    str(output_png),

                "Generated":
                    output_png.exists(),
            }
        )

        log(
            f"3D figure generated: "
            f"{protein_change}"
        )

    except Exception as exc:

        log(
            f"WARNING: 3D figure failed for "
            f"{protein_change}: {exc}"
        )

        pymol_figure_records.append(
            {
                "Protein_Change":
                    protein_change,

                "Position":
                    position,

                "Figure":
                    str(output_png),

                "Generated":
                    False,
            }
        )

    finally:

        try:

            cmd.reinitialize()

        except Exception:

            pass


pymol_figure_df = pd.DataFrame(
    pymol_figure_records
)

pymol_figure_table = (
    TABLE_DIR
    / "Table_S13_9_PyMOL_3D_figure_inventory.csv"
)

pymol_figure_df.to_csv(
    pymol_figure_table,
    index=False
)


# =============================================================================
# FINAL QC
# =============================================================================

subsection(
    "FINAL STEP 13 QUALITY CONTROL"
)

qc = {}


qc[
    "Step9F_File_Exists"
] = step9f_file.exists()

qc[
    "Step9F_Variant_Count_82"
] = len(df) == 82

qc[
    "Structural_Candidate_Count_9"
] = len(structural_df) == 9

qc[
    "Expected_Nine_Variants"
] = (
    observed_changes
    == expected_protein_changes
)

qc[
    "WT_PDB_Exists"
] = wt_pdb_file.exists()

qc[
    "WT_Chain_A_Valid"
] = (
    wt_chain is not None
    and
    len(wt_residues) > 0
)

qc[
    "PyMOL_Import"
] = True

qc[
    "All_9_Mutants_Generated"
] = (
    len(mutant_paths) == 9
)

qc[
    "All_9_Mutants_Validated"
] = (
    len(mutation_validation_df) == 9
    and
    mutation_validation_df[
        "Mutant_Residue_Validated"
    ].all()
)

qc[
    "All_9_Structural_Comparisons"
] = (
    len(comparison_df) == 9
)

qc[
    "All_9_RMSD_Values"
] = (
    comparison_df[
        "Global_CA_RMSD_A"
    ].notna().all()
    and
    comparison_df[
        "Local_CA_RMSD_A"
    ].notna().all()
)

qc[
    "All_9_pLDDT_Values"
] = (
    plddt_all_df[
        "pLDDT"
    ].notna().all()
)

qc[
    "All_9_Ranking_Values"
] = (
    ranking_output[
        "Structural_Impact_Index"
    ].notna().all()
)

qc[
    "Table_1_Exists"
] = table1.exists()

qc[
    "Table_2_Exists"
] = table2.exists()

qc[
    "Table_3_Exists"
] = table3.exists()

qc[
    "Table_4_Exists"
] = table4.exists()

qc[
    "Table_5_Exists"
] = table5.exists()

qc[
    "Table_6_Exists"
] = table6.exists()

qc[
    "Table_7_Exists"
] = table7.exists()

qc[
    "Table_8_Exists"
] = table8.exists()

qc[
    "Figure_1_Exists"
] = figure1.exists()

qc[
    "Figure_2_Exists"
] = figure2.exists()

qc[
    "Figure_3_Exists"
] = figure3.exists()

qc[
    "Figure_4_Exists"
] = figure4.exists()

qc[
    "Figure_5_Exists"
] = figure5.exists()

qc[
    "Figure_6_Exists"
] = figure6.exists()

qc[
    "Figure_7_Exists"
] = figure7.exists()

qc[
    "PyMOL_3D_Figures_At_Least_9"
] = (
    len(
        pymol_figure_df.loc[
            pymol_figure_df[
                "Generated"
            ]
            == True
        ]
    )
    == 9
)


for label, passed in qc.items():

    status(
        label,
        passed
    )


overall_qc_pass = all(
    qc.values()
)


# =============================================================================
# QC JSON
# =============================================================================

qc_json_file = (
    QC_DIR
    / "Step13_final_QC_report.json"
)

qc_report = {

    "project":
        PROJECT_NAME,

    "step":
        13,

    "pymol_version":
        pymol_version,

    "step9f_file":
        step9f_file,

    "wt_pdb":
        wt_pdb_file,

    "structural_candidate_count":
        len(structural_df),

    "mutant_count":
        len(mutant_paths),

    "comparison_count":
        len(comparison_df),

    "qc":
        qc,

    "overall_qc":
        (
            "PASS"
            if overall_qc_pass
            else "FAIL"
        ),

    "methodology": {

        "WT_reference":
            "Validated Step 10 PNPLA3 WT PDB",

        "mutant_generation":
            "PyMOL mutagenesis wizard",

        "residue_position_source":
            "Step 9F Protein_Position",

        "global_CA_RMSD":
            "Biopython Superimposer",

        "global_backbone_RMSD":
            "Biopython Superimposer using N/CA/C atoms",

        "local_CA_RMSD":
            "C-alpha RMSD within +/-10 residues",

        "heavy_atom_contact_cutoff_A":
            CONTACT_DISTANCE,

        "candidate_polar_contact_cutoff_A":
            POLAR_CONTACT_DISTANCE,

        "local_environment_cutoff_A":
            LOCAL_ENVIRONMENT_DISTANCE,

        "energy_minimization":
            False,

        "molecular_dynamics":
            False,
    },

    "important_interpretation":

        (
            "The comparative structural impact index is an "
            "analysis-specific structural comparison metric. "
            "It is not a pathogenicity probability and must "
            "not be interpreted as equivalent to AlphaMissense, "
            "CADD, REVEL, or clinical evidence. The mutant "
            "structures are PyMOL side-chain-remodeled models "
            "based on the validated Step 10 WT structure. "
            "They have not undergone energy minimization or "
            "molecular dynamics. Candidate polar contacts are "
            "heavy-atom proximity observations rather than "
            "definitive hydrogen bonds."
        ),
}

write_json(
    qc_json_file,
    qc_report
)


# =============================================================================
# FINAL SUMMARY
# =============================================================================

summary_file = (
    STEP13_DIR
    / "Step13_final_summary.txt"
)

summary_lines = [

    "STEP 13 — COMPARATIVE STRUCTURAL ANALYSIS",
    "=" * 72,
    "",

    f"Structural candidates analyzed: "
    f"{len(comparison_df)}",

    f"WT reference: {wt_pdb_file}",

    f"PyMOL version: {pymol_version}",

    "",

    "MUTANT GENERATION",
    "-" * 72,

    "All mutants were generated using the PyMOL mutagenesis wizard.",

    "No residue-name-only substitution was used.",

    "No energy minimization was performed.",

    "No molecular dynamics was performed.",

    "",

    "FINAL STRUCTURAL RANKING",
    "-" * 72,
]


for _, row in ranking_output.iterrows():

    summary_lines.append(
        (
            f"Rank {int(row['Structural_Impact_Rank']):2d}: "
            f"{row['Protein_Change']} | "
            f"Impact={row['Structural_Impact_Index']:.3f} | "
            f"Local Cα RMSD="
            f"{row['Local_CA_RMSD_A']:.4f} Å | "
            f"WT polar="
            f"{int(row['WT_Polar_Contact_Count'])} | "
            f"Mutant polar="
            f"{int(row['Mutant_Polar_Contact_Count'])} | "
            f"Lost contacts="
            f"{int(row['Contacts_Lost'])}"
        )
    )


summary_lines.extend(
    [
        "",
        "QUALITY CONTROL",
        "-" * 72,
        (
            f"Overall Step 13 QC: "
            f"{'PASS' if overall_qc_pass else 'FAIL'}"
        ),
        "",
        "SCIENTIFIC INTERPRETATION NOTE",
        "-" * 72,
        (
            "Step 13 provides comparative structural evidence "
            "for the nine prioritized variants. Very small "
            "global or local RMSD values should not by themselves "
            "be interpreted as evidence of functional neutrality. "
            "Structural interpretation should integrate residue "
            "chemistry, contact changes, catalytic-context "
            "distances, pLDDT confidence, and the computational "
            "evidence already established in Steps 9F–12."
        ),
        "",
        (
            "The structural impact index is an internal comparative "
            "ranking metric and is not a clinical pathogenicity score."
        ),
        "",
        (
            "The next downstream analyses should use the prioritized "
            "structural evidence together with therapeutic target/"
            "binding-site analysis, ligand screening, molecular "
            "docking, molecular dynamics, ADMET evaluation, and "
            "independent biological validation."
        ),
        "",
    ]
)


summary_file.write_text(
    "\n".join(
        summary_lines
    ),
    encoding="utf-8"
)


# =============================================================================
# OUTPUT INVENTORY
# =============================================================================

subsection(
    "STEP 13 FINAL OUTPUT INVENTORY"
)

output_files = {

    "WT_reference":
        wt_reference_copy,

    "Table_S13_1":
        table1,

    "Table_S13_2":
        table2,

    "Table_S13_3":
        table3,

    "Table_S13_4":
        table4,

    "Table_S13_5":
        table5,

    "Table_S13_6":
        table6,

    "Table_S13_7":
        table7,

    "Table_S13_8":
        table8,

    "Table_S13_9":
        pymol_figure_table,

    "Figure_S13_1":
        figure1,

    "Figure_S13_2":
        figure2,

    "Figure_S13_3":
        figure3,

    "Figure_S13_4":
        figure4,

    "Figure_S13_5":
        figure5,

    "Figure_S13_6":
        figure6,

    "Figure_S13_7":
        figure7,

    "QC_report":
        qc_json_file,

    "Final_summary":
        summary_file,
}


for label, path in output_files.items():

    exists = Path(
        path
    ).exists()

    log(
        f"{label:<25} "
        f"{'CREATED' if exists else 'MISSING'}"
    )

    if exists:

        log(
            f"    {path}"
        )


# =============================================================================
# FINAL STATUS
# =============================================================================

section(
    "STEP 13 COMPLETE"
)

if overall_qc_pass:

    log("")
    log(
        "FINAL STEP 13 QC: PASS"
    )

    log("")
    log(
        "All 9 prioritized PNPLA3 structural candidates "
        "were successfully modeled and comparatively analyzed."
    )

    log("")
    log(
        "Mutant structures:"
    )

    for protein_change, path in mutant_paths.items():

        log(
            f"    {protein_change}: {path}"
        )

    log("")
    log(
        "Final structural ranking:"
    )

    for _, row in ranking_output.iterrows():

        log(
            f"    Rank "
            f"{int(row['Structural_Impact_Rank'])}: "
            f"{row['Protein_Change']} "
            f"(Impact="
            f"{row['Structural_Impact_Index']:.3f})"
        )

    log("")
    log(
        f"QC report: {qc_json_file}"
    )

    log(
        f"Final summary: {summary_file}"
    )

    log("")
    log(
        "Step 13 outputs are ready for downstream "
        "integrated structural interpretation."
    )

else:

    log("")
    log(
        "FINAL STEP 13 QC: FAIL"
    )

    log(
        f"Review QC report: {qc_json_file}"
    )

    sys.exit(1)


# =============================================================================
# CLOSE PYMOL
# =============================================================================

try:

    cmd.quit()

except Exception:

    pass